### ISSUE TITLE
Some Particles Display Incorrectly

### ISSUE THREAD

**Issue by Darmandir** [Asek3/Oculus#267]
### What happened?

Particles underwater look to be displaying incorrectly. Attached is an example of water particles with Oculus enabled (mind that I do also have Flywheel enabled, maybe this is an incompatibility?)

### Screenshots

![2022-12-31_13 20 57](https://user-images.githubusercontent.com/45914359/210154178-4a6407c2-ce1a-4e61-abc4-b3f0ceff14a0.png)

### Minecraft Version

Minecraft 1.18.2

### Oculus Version

oculus-1.4.3.jar

### Rubidium Version

rubidium-0.5.4.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1060

### Java Version

17.0.1

**Comment by supershorty1** [comment]
having same problem

**Comment by CAJElevado** [comment]
I'm having this problem with the same versions of Rubidium and Oculus and with or without Flywheel.

Edit: The mods' prev. versions lack this issue, so I'm using those for now.

**Comment by m-barneto** [comment]
Also getting this issue, except its for all particles. It also makes the particle's texture blurred for me.

**Comment by supershorty1** [comment]
seems fixed in latest version

**Comment by dantaeusb** [comment]
Have this periodically on M1 SoC, Minecraft 1.19.2, Oculus 1.6.9, Rubidium 0.6.2c, Connectedness 2.0.1b.

Disappeared after I've disabled and re-enabled some resource packs (Primary Resource Pack – Stay True + Mahi's Connected Grass + ComputerCreate).

![2024-02-06_01 03 33](https://github.com/Asek3/Oculus/assets/4356112/6962f80d-a881-4f7e-86b6-7f8059adbb30)

**Comment by TerravoltPrime** [comment]
it's not working for me

**Comment by jaybeeees** [comment]
I'm still getting this bug with all particles, vanilla or modded, regardless of whether or not I have shaders enabled, or even what specific shader is enabled. It looks to me like they're being scaled up in some way. Some are fuzzy while others are smoothed out. Uninstalling Oculus fixes this issue. Very rarely this bug will momentarily fix itself, but I haven't figured out how to recreate that.

Examples of both kinds of distortion:
<img width="1280" alt="Screenshot 2024-06-28 at 4 17 09 PM" src="https://github.com/Asek3/Oculus/assets/172992885/a1c9e3f2-aabc-42f0-8cc7-53b134bf2e68">
<img width="1280" alt="Screenshot 2024-06-28 at 4 17 47 PM" src="https://github.com/Asek3/Oculus/assets/172992885/f917be57-c838-495f-be4a-b7f2c7edc48c">

Oculus 1.6.9, Minecraft 1.19.2, Embeddium 3.1.8

**Comment by ChicknTurtle** [comment]
Still happening with Oculus 1.7.0, Minecraft 1.20.1, NeoForge 47.1.106, Embeddium 0.3.31
![image](https://github.com/user-attachments/assets/0890a667-be83-4a2b-a653-47e60489c124)

**Comment by ChicknTurtle** [comment]
Reloading textures with F3+T temporarily fixes the issue

**Comment by goombamaui** [comment]
It seems like the issue occurs once certain particles are displayed. For example, I was using oculus 1.8.0, embeddium 0.3.31 on a 1.20.1 modpack with complementary shaders on a mac (silicon). Particles look normal until casting a spell with Ars Nouveau (which has blurry purple particles), after which all particles continue to look blurry until texture reload. Sometimes, using F3+T does not fix the issue, which I guess happens because one of these "problem particles" is continuously being generated which causes the problem to immediately reappear.

**Comment by Greatbeing2001** [comment]
The issue is triggered by rain. If you install pretty rain (NOT PARTICLE RAIN) it will solve the issue.
