### ISSUE TITLE
Create Rope Pulley rope invisible

### ISSUE THREAD

**Issue by Tohricat** [Asek3/Oculus#75]
### What happened?

The rope pulley from Create has an invisible rope when it's moving. The rope also doesn't render on the block itself. 

### Minecraft Version

Minecraft 1.18.2

### Iris Version

Oculus mc1.18.2-1.2.4

### Sodium Version

Rubidium mc1.18.2-0.5.2a

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 3070 Laptop GPU

### Java Version

Java 17

**Comment by Hiconel** [comment]
I have the same issue. Oddly enough it doesn't happen with the hose pulley

**Comment by Asek3** [comment]
Should be fixed in latest versions of mods

**Comment by Hiconel** [comment]
As far as I can tell, it seems to be working great with /flywheel backend instancing, however as soon as I turn on any shaders, the rope is only visible again once nothing is moving. Don't know if that should have a new issue created for it, but I thought I would mention it here first.

![image](https://user-images.githubusercontent.com/1748758/184985863-03359224-0972-44da-902f-831f11fda973.png)

**Comment by Zhenfaix** [comment]
Did you guys manage to get the pulley to render normally with shaders? I have updated Create, Rubidium, flywheel, and Oculus for 1.18.2 as of today and the problem of the rope not rendering during motion or inside the pulley still persists.
